@ECHO OFF
XCOPY "./src/ATN.READ/bin/%CONFIGURATION%/%FRAMEWORK%/%RUNTIME%/*.*" "./dist/%RUNTIME%/ATN.READ/" /E /I /F /Y
XCOPY "./src/ATN.CALC/bin/%CONFIGURATION%/%FRAMEWORK%/%RUNTIME%/*.*" "./dist/%RUNTIME%/ATN.CALC/" /E /I /F /Y
XCOPY "./src/ATN.WRITE/bin/%CONFIGURATION%/%FRAMEWORK%/%RUNTIME%/*.*" "./dist/%RUNTIME%/ATN.WRITE/" /E /I /F /Y
